stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - data/raw_data.csv
    outs:
      - data/processed_data.csv
  train:
    cmd: python scripts/train.py
    deps:
      - data/processed_data.csv
    outs:
      - models/model.pkl
